version: 2
jobs:
  build:
    working_directory: ~/comms-kafka-serialization

    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - restore_cache:
          keys:
            - sbt-version--{{ checksum "project/build.properties" }}
            - build--{{ checksum "build.sbt" }}-sbt-plugin--{{ checksum "project/plugins.sbt" }}
      - run: sbt -mem 1500 update
      - save_cache:
          key: sbt-version--{{ checksum "project/build.properties" }}
          paths:
            - "~/.sbt"
      - save_cache:
          key: build--{{ checksum "build.sbt" }}-sbt-plugin--{{ checksum "project/plugins.sbt" }}
          paths:
            - "~/.ivy2/cache"
            - "~/.m2"
            - "target/resolution-cache"
            - "project/target/resolution-cache"

      - run: sbt -mem 2048 +test
