version: 2
jobs:
  build:
    working_directory: ~/comms-kafka-serialization

    docker:
    - image: circleci/openjdk:8-jdk

    steps:
      - restore_cache:
          key: dependency-cache
          paths:
            - "~/.sbt"
            - "target/resolution-cache"
            - "project/target/resolution-cache"
      - checkout
      - run: sbt -mem 1500 update
      - save_cache:
          key: dependency-cache
          paths:
            - "~/.sbt"
            - "target/resolution-cache"
            - "project/target/resolution-cache"

      - run: sbt -mem 2048 +test
